extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let generated_code_warning = "/*
* ================================================================================================
*  WARNING: This file is automatically generated by cbindgen. Manual edits are likely to be lost.
* ================================================================================================
*/";
    let edhoc_features_define = "#ifndef EDHOC_FEATURES
#define EDHOC_FEATURES RUST_CRYPTOCELL310
#endif";

    let cbindgen_builder = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header(generated_code_warning)
        .with_include("edhoc_consts.h")
        .with_after_include(edhoc_features_define)
        .with_parse_expand_all_features(false);

    cbindgen_builder
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("../include/edhoc_rs.h");
}
